openapi: 3.0.3
info:
  title: Agence de Voyages API
  description: API pour la gestion des comptes clients et des réservations de voyages
  version: 1.0.0
  
servers:
  - url: http://localhost:8080/v1/api/
    description: Development server

tags:
  - name: clients
    description: Opérations liées aux clients
  - name: voyages
    description: Opérations liées aux voyages
  - name: reservations
    description: Opérations liées aux réservations
  - name: messages
    description: Opérations liées aux messages à l'agence
  - name: agents
    description: Opérations spécifiques aux agents de l'agence

paths:
  /clients:
    post:
      summary: Créer un compte client
      description: Permet aux clients de créer un compte avec leurs informations personnelles.
      tags:
        - clients
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                adresse:
                  type: string
                telephone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Compte client créé avec succès

  /clients/{clientId}:
    get:
      summary: Obtenir les détails du compte client
      description: Retourne les informations personnelles d'un client spécifié par {clientId}.
      tags:
        - clients
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails du compte client récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  nom:
                    type: string
                  adresse:
                    type: string
                  telephone:
                    type: string
                  email:
                    type: string

    put:
      summary: Mettre à jour les informations du compte client
      description: Permet au client de mettre à jour ses informations personnelles.
      tags:
        - clients
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                adresse:
                  type: string
                telephone:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Informations du compte client mises à jour avec succès

  /clients/{clientId}/password:
    put:
      summary: Modifier le mot de passe du compte client
      description: Permet au client de modifier son mot de passe.
      tags:
        - clients
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                new_password:
                  type: string
      responses:
        '200':
          description: Mot de passe du compte client modifié avec succès

  /voyages:
    get:
      summary: Rechercher des voyages disponibles
      description: Permet aux clients de rechercher et de consulter les voyages proposés.
      tags:
        - voyages
      parameters:
        - in: query
          name: destination
          schema:
            type: string
          description: Destination du voyage recherché
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: Date du voyage recherché
      responses:
        '200':
          description: Liste des voyages disponibles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    destination:
                      type: string
                    date:
                      type: string
                      format: date
                    prix:
                      type: number
                    disponibilite:
                      type: boolean

  /reservations:
    post:
      summary: Effectuer une réservation de voyage
      description: Permet aux clients de réserver un voyage.
      tags:
        - reservations
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: string
                voyageId:
                  type: string
                date:
                  type: string
                  format: date
      responses:
        '201':
          description: Réservation effectuée avec succès

    delete:
      summary: Annuler une réservation de voyage
      description: Permet aux clients d'annuler une réservation de voyage.
      tags:
        - reservations
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: reservationId
          schema:
            type: string
          description: ID de la réservation à annuler
      responses:
        '204':
          description: Réservation annulée avec succès

  /messages:
    post:
      summary: Envoyer un message à l'agence de voyage
      description: Permet aux clients d'envoyer un message à l'agence de voyage.
      tags:
        - messages
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: string
                message:
                  type: string
      responses:
        '201':
          description: Message envoyé avec succès

  /agents/reservations:
    get:
      summary: Consulter les réservations des clients
      description: Permet aux agents de l'agence de consulter les réservations des clients.
      tags:
        - agents
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste des réservations clients récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    clientId:
                      type: string
                    voyageId:
                      type: string
                    date:
                      type: string
                      format: date

  /agents/voyages:
    post:
      summary: Ajouter un nouveau voyage
      description: Permet aux agents de l'agence d'ajouter un nouveau voyage.
      tags:
        - agents
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                date:
                  type: string
                  format: date
                prix:
                  type: number
                disponibilite:
                  type: boolean
      responses:
        '201':
          description: Voyage ajouté avec succès

  /agents/voyages/{voyageId}:
    put:
      summary: Modifier les détails d'un voyage existant
      description: Permet aux agents de l'agence de modifier les détails d'un voyage existant.
      tags:
        - agents
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: voyageId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                date:
                  type: string
                  format: date
                prix:
                  type: number
                disponibilite:
                  type: boolean
      responses:
        '200':
          description: Détails du voyage modifiés avec succès

    get:
      summary: Obtenir les détails d'un voyage
      description: Retourne les détails d'un voyage spécifié par {voyageId}.
      tags:
        - agents
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: voyageId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails du voyage récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  destination:
                    type: string
                  date:
                    type: string
                    format: date
                  prix:
                    type: number
                  disponibilite:
                    type: boolean

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT              